name: ProofReader Action
description: An action that checks ce
author: samdouble

inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: World

branding:
  icon: activity
  color: green

runs:
  using: node20
  main: 'dist/index.js'
